### ISSUE TITLE
LoadBalancer doesn't seem to deploy with correct port range

### ISSUE THREAD

**Issue by jacobhpAZ** [GoogleCloudPlatform/looker-hosting-reference-implementations#6]
I'm a bit unsure on this as I couldn't find any code here that specifically refers to this port range for LoadBalancer (Note: Am not overly familiar with Terraform or Kubernetes).

When I attempted to deploy a Kubernetes instance I found that after I had completed the steps, the DNS url did not work, nor could I connect to the web app using the LoadBalancer IP and port.

Upon deployment following the steps, the LoadBalancer was configured with the following port range:
<img width="868" alt="old-fail-kube" src="https://user-images.githubusercontent.com/105797501/177560385-47886fb5-2c30-4ee8-b2bd-d2713b4ab837.PNG">

This seemed to cause the pod health check to fail and the web app not to respond.

When I tried deploying a new service via kubectl:
```bash
kubectl expose deployment looker-clustered -n looker-dev --type=LoadBalancer --name myservice
```

A load balancer was created with the following range:
<img width="829" alt="new-working-kube" src="https://user-images.githubusercontent.com/105797501/177560492-84b0b14b-5de8-4308-a6a8-9c5e1d3e78f4.PNG">

For this, the health check worked fine and I was able to connect to the web app. I hope this is enough info, please let me know if any more is required.

**Comment by JCPistell** [comment]
From what I can see in your screenshot the load balancer config looks correct - we handle connectivity to your cluster via an [ingress controller](https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/) to an ingress-nginx workload/service (see the [base](https://github.com/GoogleCloudPlatform/looker-hosting-reference-implementations/blob/main/kubernetes/manifests/looker/base/looker_ingress.yaml) and the associated [patch.](https://github.com/GoogleCloudPlatform/looker-hosting-reference-implementations/blob/main/kubernetes/manifests/looker/templates/patch_ingress_annotations.tpl))
 
The first thing I'd check is to ensure you have deployed the [ingress-nginx](https://github.com/kubernetes/ingress-nginx) workload correctly. If that all looks good the next most common source of problems  is your TLS certificate provisioning via cert-manager. Their [troubleshooting docs](https://cert-manager.io/docs/faq/acme/) can help you narrow down any potential issues.

You can also quickly confirm if the IP address listed in your screenshot lines up with both the IP address in your DNS record set and your ingress-nginx LoadBalancer service IP, named `ingress-nginx-controller` by default. Find it via `kubectl get svc -n ingress-nginx`

This is all my best guesses based on past experience - I hope it's useful. See if this helps and feel free to come back with any additional questions and/or more info.

**Comment by JCPistell** [comment]
Closing for now - let us know if you need anything else
